#+AUTHOR: Timo Tuominen
#+TITLE: Suorituskykyinen sovellusarkkitehtuuri Java-natiivirajapintaa hyödyntävälle Android-sovellukselle
#+LaTeX_CLASS: gradu
#+LaTeX_CLASS_OPTIONS: [gradu]

#+BEGIN_abstract
#+INCLUDE: "chapters/abstract.org"
#+END_abstract

#+LATEX: \mytableofcontents
#+LATEX: \onehalfspacing
#+LATEX: \newpage

#+LATEX: \definecolor{listingc}{rgb}{0.98,0.98,0.98}
#+LATEX: \newcommand{\todo}[1]{}


* Johdanto
#+INCLUDE: "../gen/chapters/intro.org" :minlevel 1
* Yleiskatsaus Android-järjestelmään
#+INCLUDE: "../gen/chapters/android_summary.org" :minlevel 1
* Suorituskyky ohjelmistokehityksessä
#+INCLUDE: "../gen/chapters/performance.org" :minlevel 1
* Java-natiivirajapinta
#+INCLUDE: "../gen/chapters/jni.org" :minlevel 1

#+LATEX: \newpage

* Koeasetelman kuvaus 

** Mittaussovellus
   Tutkielmaa varten ohjelmoidun synteettisen mittausovelluksen (microbenchmarking suite)
   esittely.
*** Sovelluksen kokonaisarkkitehtuuri
    2 sivua\newline 20. 1. 2014

    Sovelluksen komponentit.
    
*** Toteutuksen ominaispiirteitä
    4 sivua\newline 27. 1. 2014

    Mittaussovellukseen kohdistuvia erityishaasteita ja
    niiden ratkaisuja.

** Mittauskohde
*** Luokitellut JNI-operaatiot
    5 sivua\newline 2. 2. 2014

    JNI-operaatiot kategorisoidaan ja esitellään tiiviisti ja kommentoidaan
    niiden mittaamiseen liittyviä haasteita. Kategoriat ovat:
    - Viitteidenhallinta
    - Olioiden käsittely
    - Kenttien ja metodien löytäminen
    - Kenttien ja metodien käyttö
    - Merkkijonojen ja taulukoiden käsittely
    - Tehostetut IO-operaatiot (NIO)
    
*** Sivuutetut operaatiot
    1 sivu\newline 3. 2. 2014

    Mittausten ulkopuolelle jääneet JNI-funktiot perusteluineen.
    - Natiivimetodien rekisteröinti
    - Luokkaoperaatiot
    - Reflektio
    - Virtuaalikone ja versiontarkistus

** Tulosten käsittelymenetelmät
*** Analyysiohjelma
    2 sivua\newline 9. 2. 2014

    Yleisesittely tulosten analysointiin käytettävästä ohjelmasta.
*** Tilastolliset menetelmät
    2 sivua\newline 10. 2. 2014

    Käytetyt tilastolliset menetelmät.
* Mittaustulokset
** Vasteaikamittaukset
    5 sivua\newline 17. 2. 2014

    Raakatulokset.
** Kutsuprofiilit
    5 sivua\newline 24. 2. 2014

    Raakatulokset.
** Yhteenveto tuloksista
    3 sivua\newline 10. 3. 2014

    Molempien mittausmenetelmien tulosten yhdistäminen.
* Tulosten analyysi
** JNI-kuormitusmalli
    4 sivua\newline 17. 3. 2014

    Yksinkertainen malli, joka kertoo miten JNI-rajapinnan aiheuttaman
    kuormituksen voi ennustaa sen käyttötavasta.
** Sovellusarkkitehtuurivaihtoehdot
    5 sivua\newline 24. 3. 2014

    Esitellään 2-3 vaihtoehtoa JNI-sovelluksen kokonaisrakenteelle.
** Arkkitehtuurisuositukset
    2 sivua\newline 31. 3. 2014

    Analysoidaan mallin perusteella paras arkkitehtuurimalli.
** Haasteet ja puutteet
    4 sivua\newline 7. 4. 2014

    Käsitellään tulosten tieteellistä luotettavuutta ja erityisesti sitä,
    missä määrin mittaukset selviävät synteettisen mittaamisen sudenkuopista, ja
    miten tutkimuskohdetta voisi paremmin mitata tulevaisuudessa.
* Johtopäätökset
    4 sivua\newline 14. 4. 2014

    Yhteenveto edellisen 2 luvun tuloksista.

#+LATEX: \newpage
#+LATEX: \bibliographystyle{templates/tktl}
#+LATEX: \bibliography{bib/main}

