package "fi.helsinki.cs.tituomin.nativebenchmark" {
  package "benchmark" {
    () run
    [Benchmark]
    [Benchmark] - run
  }
  [NativeBenchmark] ..> run
}
[perf record] - exec
[NativeBenchmark] ..> exec
