
node "Android-laite" {
  frame "Tiedostojärjestelmä" {
    database mittaustulokset
  }
  frame "Linux" {
    frame "Dalvik" {
      package "fi.helsinki.cs.tituomin.nativebenchmark" {
        () run
        [Benchmark]
        [Benchmark] - run
        [Native Benchmark] ..> run
      }
    }
    [perf record] - exec
    [Native Benchmark] ..> exec
  }
}

node "Kehitysympäristö" {

  frame "Käännöstyökalut" {
    [Benchmark generator] --> [Benchmark] : " generoi"
  }
  [mittaustulokset] <- [Native Benchmark]
  [mittaustulokset] <- [perf record]

  frame "Analyysi" {
    [Benchmark analyzer] -> [mittaustulokset] : " analysoi"
  }
}


