package "fi.helsinki.cs.tituomin.nativebenchmark" {
  package "benchmark" {
    () run
    [Benchmark]
    [Benchmark] - run
  }
  package "measuringtool" {
    [JavaSystemNanoResponseTimeRecorder] -- () start
    [LinuxPerfRecordTool] -- () start
  }
  [BenchmarkRunner] .> start
  [LinuxPerfRecordTool] .> run
  [JavaSystemNanoResponseTimeRecorder] .> run
}
package "libnativebenchmark" {
  [nativerunners.c] - runInternal
  [nativebenchmark.c] - nativemethod
}
'[perf record] - exec
'[LinuxPerfRecordTool] ..> exec
