package "fi.helsinki.cs.tituomin.nativebenchmark" {
  package "measuringtool" {
    () start -- [MeasuringTool]
    [JavaSystemNanoResponseTimeRecorder] -|> [MeasuringTool]
    [MeasuringTool] <|- [LinuxPerfRecordTool]
  }

  package "benchmark" {
    () run -- [Benchmark]
    () method_stub
    method_stub -- [JavaCounterparts]
    [J2JBenchmark]
    [J2CBenchmark]
    () runInternal as runInternalJava
    [J2JBenchmark] -- () runInternalJava
    [J2CBenchmark] -- () runInternalJava
    [C2CBenchmark]
    [C2JBenchmark]

    [Benchmark] <|-- [J2JBenchmark]
    [Benchmark] <|-- [J2CBenchmark]
    [Benchmark] <|-- [C2CBenchmark]
    [Benchmark] <|-- [C2JBenchmark]

    note bottom of runInternalJava : Java-kielinen lähtösilmukka,\njossa kutsutaan kohdemetodia tai -funktiota
    note left of method_stub : Java-kielinen tyhjä kohdemetodi

  }

  [BenchmarkRunner] ..> start
  [MeasuringTool] ..> run

  package "libnativebenchmark" {
    () runInternal
    () method_stub as nativemethod_stub
    [nativerunners.c] -- runInternal
    nativemethod_stub -- [nativebenchmark.c]

    note bottom of runInternal : Natiivilähtösilmukka, jossa kutsutaan\nkohdemetodia- tai funktiota
    note top of nativemethod_stub : C-kielinen\ntyhjä kohdemetodi

  }
}

[C2CBenchmark] ..> runInternal
[C2JBenchmark] ..> runInternal
[J2CBenchmark] ..> nativemethod_stub
[nativerunners.c] .> nativemethod_stub
[nativerunners.c] .> method_stub
[J2JBenchmark] ..> method_stub
